import type { AppState, Post, Comment, User, Subreddit } from "./types";

// Stable IDs so cross-references are consistent
const USER_IDS = {
  demouser: "u-00000001-demo-user-0001",
  techguru: "u-00000002-tech-guru-0002",
  naturelover: "u-00000003-nature-lov-0003",
} as const;

const SUB_IDS = {
  programming: "s-00000001-programming-01",
  askreddit: "s-00000002-askreddit-0002",
  pics: "s-00000003-pics-00000003",
  gaming: "s-00000004-gaming-000004",
  science: "s-00000005-science-00005",
} as const;

function ago(days: number, hours: number = 0, minutes: number = 0): number {
  return Date.now() - days * 24 * 60 * 60 * 1000 - hours * 60 * 60 * 1000 - minutes * 60 * 1000;
}

function makePostId(n: number): string {
  return `p-${String(n).padStart(8, "0")}-post`;
}

function makeCommentId(n: number): string {
  return `c-${String(n).padStart(8, "0")}-cmnt`;
}

export function createSeedData(): AppState {
  // --- Users ---
  const users: User[] = [
    {
      id: USER_IDS.demouser,
      username: "demouser",
      password: "demo123",
      createdAt: ago(120),
      avatar: "\ud83e\udd16",
      bio: "Just a demo account exploring the Reddit clone. I like technology and memes.",
      savedPosts: [makePostId(5), makePostId(12)],
      savedComments: [makeCommentId(3)],
      upvotedPosts: [
        makePostId(2),
        makePostId(5),
        makePostId(8),
        makePostId(10),
        makePostId(14),
        makePostId(17),
      ],
      downvotedPosts: [makePostId(11)],
      upvotedComments: [makeCommentId(2), makeCommentId(5), makeCommentId(9)],
      downvotedComments: [],
      following: [USER_IDS.techguru],
      blocked: [],
      history: [makePostId(1), makePostId(2), makePostId(5), makePostId(10)],
    },
    {
      id: USER_IDS.techguru,
      username: "techguru",
      password: "tech123",
      createdAt: ago(200),
      avatar: "\ud83d\udcbb",
      bio: "Software engineer and open source enthusiast. Rust and TypeScript advocate.",
      savedPosts: [makePostId(1), makePostId(3)],
      savedComments: [],
      upvotedPosts: [
        makePostId(1),
        makePostId(3),
        makePostId(6),
        makePostId(9),
        makePostId(15),
        makePostId(19),
      ],
      downvotedPosts: [makePostId(7)],
      upvotedComments: [makeCommentId(1), makeCommentId(7)],
      downvotedComments: [makeCommentId(4)],
      following: [USER_IDS.demouser, USER_IDS.naturelover],
      blocked: [],
      history: [makePostId(1), makePostId(3), makePostId(6), makePostId(9)],
    },
    {
      id: USER_IDS.naturelover,
      username: "naturelover",
      password: "nature123",
      createdAt: ago(90),
      avatar: "\ud83c\udf3f",
      bio: "Amateur photographer and hiking enthusiast. Capturing the beauty of the natural world.",
      savedPosts: [makePostId(8), makePostId(16)],
      savedComments: [makeCommentId(6)],
      upvotedPosts: [makePostId(4), makePostId(8), makePostId(12), makePostId(16), makePostId(20)],
      downvotedPosts: [],
      upvotedComments: [makeCommentId(3), makeCommentId(8)],
      downvotedComments: [],
      following: [USER_IDS.techguru],
      blocked: [],
      history: [makePostId(4), makePostId(8), makePostId(12), makePostId(16)],
    },
  ];

  // --- Subreddits ---
  const subreddits: Subreddit[] = [
    {
      id: SUB_IDS.programming,
      name: "programming",
      description:
        "Computer programming discussion and news. Share articles, tutorials, and interesting projects.",
      banner: "#0079D3",
      icon: "\ud83d\udcbb",
      rules: [
        {
          title: "No memes or low-effort content",
          description: "Only substantial programming-related content.",
        },
        {
          title: "No job postings",
          description: "Use dedicated subreddits for job listings.",
        },
      ],
      createdAt: ago(365),
      createdBy: USER_IDS.techguru,
      members: [USER_IDS.demouser, USER_IDS.techguru, USER_IDS.naturelover],
      moderators: [USER_IDS.techguru],
      bannedUsers: [],
      flairs: ["Discussion", "Tutorial", "Project", "News", "Question"],
    },
    {
      id: SUB_IDS.askreddit,
      name: "askreddit",
      description:
        "The place to ask and answer thought-provoking questions. Share your stories and perspectives.",
      banner: "#FF4500",
      icon: "\u2753",
      rules: [
        {
          title: "Questions must be open-ended",
          description: "No yes/no questions.",
        },
        {
          title: "Be respectful",
          description: "No personal attacks or harassment.",
        },
      ],
      createdAt: ago(400),
      createdBy: USER_IDS.demouser,
      members: [USER_IDS.demouser, USER_IDS.techguru, USER_IDS.naturelover],
      moderators: [USER_IDS.demouser],
      bannedUsers: [],
      flairs: ["Serious", "Funny", "Stories", "Advice"],
    },
    {
      id: SUB_IDS.pics,
      name: "pics",
      description:
        "A community for sharing and discussing images. Photography, art, and visual content welcome.",
      banner: "#46D160",
      icon: "\ud83d\udcf7",
      rules: [
        {
          title: "No screenshots or screen captures",
          description: "Only photographs and original art.",
        },
        {
          title: "Must include source",
          description: "Credit the photographer or artist when known.",
        },
      ],
      createdAt: ago(350),
      createdBy: USER_IDS.naturelover,
      members: [USER_IDS.demouser, USER_IDS.naturelover],
      moderators: [USER_IDS.naturelover],
      bannedUsers: [],
      flairs: ["Photography", "Art", "Nature", "Architecture", "Portrait"],
    },
    {
      id: SUB_IDS.gaming,
      name: "gaming",
      description:
        "The number one gaming community. News, reviews, previews, rumors, and discussion about all things gaming.",
      banner: "#7B68EE",
      icon: "\ud83c\udfae",
      rules: [
        {
          title: "No piracy discussion",
          description: "Do not share or request pirated content.",
        },
        {
          title: "Spoilers must be tagged",
          description: "Use spoiler tags for new releases.",
        },
      ],
      createdAt: ago(300),
      createdBy: USER_IDS.demouser,
      members: [USER_IDS.demouser, USER_IDS.techguru],
      moderators: [USER_IDS.demouser],
      bannedUsers: [],
      flairs: ["News", "Discussion", "Screenshot", "Meme", "Review"],
    },
    {
      id: SUB_IDS.science,
      name: "science",
      description:
        "Science news and discussion. Peer-reviewed research, discoveries, and evidence-based analysis.",
      banner: "#2EBFA5",
      icon: "\ud83d\udd2c",
      rules: [
        {
          title: "Must link to peer-reviewed research",
          description:
            "All submissions must link to published research or credible science journalism.",
        },
        {
          title: "No speculation without evidence",
          description: "Claims must be supported by data.",
        },
      ],
      createdAt: ago(280),
      createdBy: USER_IDS.techguru,
      members: [USER_IDS.techguru, USER_IDS.naturelover],
      moderators: [USER_IDS.techguru],
      bannedUsers: [],
      flairs: ["Biology", "Physics", "Chemistry", "Space", "Environment", "Medicine"],
    },
  ];

  // --- Posts ---
  // Posts are numbered 1-20 across subreddits
  const posts: Post[] = [
    // === programming (posts 1-5) ===
    {
      id: makePostId(1),
      type: "text",
      title: "Why Rust is becoming my go-to language for backend services",
      body: "After spending 3 years with Go and Node.js, I recently moved a production service to Rust. The performance gains were significant (40% lower latency, 60% less memory), but what really sold me was the compiler catching bugs that would have made it to production in other languages.\n\n**Key takeaways:**\n- The borrow checker is painful at first but becomes second nature\n- `serde` makes JSON handling almost as easy as JavaScript\n- Error handling with `Result` is superior to exceptions\n- The ecosystem has matured significantly since 2023\n\nHappy to answer questions about the migration process.",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.programming,
      authorId: USER_IDS.techguru,
      createdAt: ago(2, 5),
      updatedAt: ago(2, 5),
      upvotes: 287,
      downvotes: 34,
      flair: "Discussion",
      spoiler: false,
      nsfw: false,
      awards: [{ type: "gold", givenBy: USER_IDS.demouser, givenAt: ago(2, 3) }],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(2),
      type: "link",
      title: "TypeScript 6.0 released with full pattern matching support",
      body: "",
      url: "https://devblogs.microsoft.com/typescript/announcing-typescript-6-0/",
      imageUrl: "",
      subredditId: SUB_IDS.programming,
      authorId: USER_IDS.demouser,
      createdAt: ago(1, 12),
      updatedAt: ago(1, 12),
      upvotes: 542,
      downvotes: 18,
      flair: "News",
      spoiler: false,
      nsfw: false,
      awards: [
        { type: "platinum", givenBy: USER_IDS.techguru, givenAt: ago(1, 10) },
        {
          type: "silver",
          givenBy: USER_IDS.naturelover,
          givenAt: ago(1, 8),
        },
      ],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(3),
      type: "text",
      title: "I built a full-stack app in a weekend using Effect-TS. Here is what I learned",
      body: "Effect-TS has been on my radar for a while, and I finally took the plunge this weekend. Built a task management app with:\n\n- Effect for the backend service layer\n- Schema for validation\n- `@effect/platform` for HTTP\n\nThe learning curve is steep but the composability is incredible. Error handling becomes a first-class concern rather than an afterthought.\n\n```typescript\nconst program = pipe(\n  getUserById(id),\n  Effect.flatMap(validatePermissions),\n  Effect.flatMap(fetchTasks),\n  Effect.catchTag('NotFound', () => Effect.succeed([]))\n)\n```\n\nThe type safety is unmatched. Every error path is tracked in the type system.",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.programming,
      authorId: USER_IDS.techguru,
      createdAt: ago(5, 8),
      updatedAt: ago(5, 8),
      upvotes: 189,
      downvotes: 22,
      flair: "Project",
      spoiler: false,
      nsfw: false,
      awards: [],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(4),
      type: "text",
      title: "What are you working on this week? (Weekly thread)",
      body: "Share your current projects, side hustles, or interesting problems you are solving. No project is too small!",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.programming,
      authorId: USER_IDS.demouser,
      createdAt: ago(0, 18),
      updatedAt: ago(0, 18),
      upvotes: 45,
      downvotes: 2,
      flair: "Discussion",
      spoiler: false,
      nsfw: false,
      awards: [],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(5),
      type: "link",
      title:
        "SQLite is not a toy database - benchmarks show it outperforming Postgres for read-heavy workloads",
      body: "",
      url: "https://avi.im/blag/2024/sqlite-not-a-toy-database/",
      imageUrl: "",
      subredditId: SUB_IDS.programming,
      authorId: USER_IDS.techguru,
      createdAt: ago(3, 2),
      updatedAt: ago(3, 2),
      upvotes: 412,
      downvotes: 67,
      flair: "News",
      spoiler: false,
      nsfw: false,
      awards: [{ type: "silver", givenBy: USER_IDS.demouser, givenAt: ago(3, 1) }],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // === askreddit (posts 6-9) ===
    {
      id: makePostId(6),
      type: "text",
      title: "What is a skill you learned in your 20s that completely changed your life?",
      body: "",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.askreddit,
      authorId: USER_IDS.demouser,
      createdAt: ago(1, 4),
      updatedAt: ago(1, 4),
      upvotes: 1823,
      downvotes: 42,
      flair: "Stories",
      spoiler: false,
      nsfw: false,
      awards: [
        { type: "gold", givenBy: USER_IDS.techguru, givenAt: ago(1, 2) },
        {
          type: "gold",
          givenBy: USER_IDS.naturelover,
          givenAt: ago(1, 1),
        },
      ],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(7),
      type: "text",
      title: "People who wake up at 5 AM every day - what do you actually do with that extra time?",
      body: "",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.askreddit,
      authorId: USER_IDS.naturelover,
      createdAt: ago(4, 6),
      updatedAt: ago(4, 6),
      upvotes: 934,
      downvotes: 88,
      flair: "Advice",
      spoiler: false,
      nsfw: false,
      awards: [],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(8),
      type: "text",
      title:
        "What is something that was considered a luxury 20 years ago but is now considered a necessity?",
      body: "",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.askreddit,
      authorId: USER_IDS.techguru,
      createdAt: ago(6, 14),
      updatedAt: ago(6, 14),
      upvotes: 2156,
      downvotes: 31,
      flair: "Funny",
      spoiler: false,
      nsfw: false,
      awards: [
        {
          type: "platinum",
          givenBy: USER_IDS.demouser,
          givenAt: ago(6, 10),
        },
      ],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(9),
      type: "text",
      title: "What is the most underrated piece of advice you have ever received?",
      body: "",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.askreddit,
      authorId: USER_IDS.demouser,
      createdAt: ago(0, 6),
      updatedAt: ago(0, 6),
      upvotes: 312,
      downvotes: 8,
      flair: "Serious",
      spoiler: false,
      nsfw: false,
      awards: [],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // === pics (posts 10-13) ===
    {
      id: makePostId(10),
      type: "image",
      title: "Caught this incredible sunset over the Pacific last evening",
      body: "Shot on my phone from a cliff near Big Sur. No filters needed.",
      url: "",
      imageUrl: "https://picsum.photos/seed/sunset-pacific/800/600",
      subredditId: SUB_IDS.pics,
      authorId: USER_IDS.naturelover,
      createdAt: ago(1, 20),
      updatedAt: ago(1, 20),
      upvotes: 3421,
      downvotes: 56,
      flair: "Nature",
      spoiler: false,
      nsfw: false,
      awards: [
        { type: "gold", givenBy: USER_IDS.demouser, givenAt: ago(1, 18) },
        { type: "silver", givenBy: USER_IDS.techguru, givenAt: ago(1, 16) },
      ],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(11),
      type: "image",
      title: "My cat decided the keyboard was a better bed than the actual bed",
      body: "",
      url: "",
      imageUrl: "https://picsum.photos/seed/cat-keyboard/800/600",
      subredditId: SUB_IDS.pics,
      authorId: USER_IDS.demouser,
      createdAt: ago(3, 10),
      updatedAt: ago(3, 10),
      upvotes: 892,
      downvotes: 145,
      flair: "Photography",
      spoiler: false,
      nsfw: false,
      awards: [],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(12),
      type: "image",
      title: "Milky Way over the Sahara Desert - 2 hour exposure composite",
      body: "Equipment: Sony A7IV, Sigma 14mm f/1.8, iOptron SkyGuider Pro tracker. This is a composite of 45 tracked exposures at 120s each, plus a foreground shot.",
      url: "",
      imageUrl: "https://picsum.photos/seed/milkyway-sahara/800/600",
      subredditId: SUB_IDS.pics,
      authorId: USER_IDS.naturelover,
      createdAt: ago(7, 3),
      updatedAt: ago(7, 3),
      upvotes: 5678,
      downvotes: 89,
      flair: "Photography",
      spoiler: false,
      nsfw: false,
      awards: [
        {
          type: "platinum",
          givenBy: USER_IDS.techguru,
          givenAt: ago(7, 1),
        },
        { type: "gold", givenBy: USER_IDS.demouser, givenAt: ago(6, 22) },
      ],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(13),
      type: "image",
      title: "Abandoned railway station in rural Japan, being reclaimed by nature",
      body: "Found this during a cycling trip through Shikoku. The station has been closed since the 1990s.",
      url: "",
      imageUrl: "https://picsum.photos/seed/japan-station/800/600",
      subredditId: SUB_IDS.pics,
      authorId: USER_IDS.naturelover,
      createdAt: ago(10, 5),
      updatedAt: ago(10, 5),
      upvotes: 2345,
      downvotes: 34,
      flair: "Architecture",
      spoiler: false,
      nsfw: false,
      awards: [{ type: "silver", givenBy: USER_IDS.demouser, givenAt: ago(10, 3) }],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // === gaming (posts 14-17) ===
    {
      id: makePostId(14),
      type: "text",
      title:
        "After 200 hours, I finally beat Elden Ring without leveling up. Here is my experience",
      body: "What started as a meme challenge turned into one of the most rewarding gaming experiences of my life. Key bosses ranked by difficulty:\n\n1. Malenia - 147 attempts\n2. Radahn (pre-nerf) - 89 attempts\n3. Maliketh - 72 attempts\n4. Godfrey - 45 attempts\n\nThe trick is mastering i-frames and learning every single attack pattern. By the end I could dodge Waterfowl Dance with my eyes closed.\n\n**Tips for anyone attempting this:**\n- Frost and bleed are your best friends\n- Spirit ashes are not cheating, use them\n- Take breaks. Seriously. The tilt is real.",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.gaming,
      authorId: USER_IDS.demouser,
      createdAt: ago(2, 8),
      updatedAt: ago(2, 8),
      upvotes: 1567,
      downvotes: 43,
      flair: "Discussion",
      spoiler: false,
      nsfw: false,
      awards: [{ type: "gold", givenBy: USER_IDS.techguru, givenAt: ago(2, 6) }],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(15),
      type: "link",
      title: "GTA VI release date confirmed for Fall 2026",
      body: "",
      url: "https://www.rockstargames.com/newswire",
      imageUrl: "",
      subredditId: SUB_IDS.gaming,
      authorId: USER_IDS.techguru,
      createdAt: ago(0, 8),
      updatedAt: ago(0, 8),
      upvotes: 4231,
      downvotes: 156,
      flair: "News",
      spoiler: false,
      nsfw: false,
      awards: [
        {
          type: "platinum",
          givenBy: USER_IDS.demouser,
          givenAt: ago(0, 6),
        },
        {
          type: "gold",
          givenBy: USER_IDS.naturelover,
          givenAt: ago(0, 5),
        },
      ],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(16),
      type: "image",
      title: "My cozy gaming setup - finally finished after 6 months of upgrades",
      body: "Specs: RTX 5080, Ryzen 9 9950X, 64GB DDR5, LG C3 42-inch as main monitor. The ambient lighting is all Govee and synced to the screen.",
      url: "",
      imageUrl: "https://picsum.photos/seed/gaming-setup/800/600",
      subredditId: SUB_IDS.gaming,
      authorId: USER_IDS.demouser,
      createdAt: ago(5, 12),
      updatedAt: ago(5, 12),
      upvotes: 876,
      downvotes: 34,
      flair: "Screenshot",
      spoiler: false,
      nsfw: false,
      awards: [],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(17),
      type: "text",
      title: "Hot take: modern games are too long and would benefit from being 15-20 hours",
      body: "I used to think longer games meant better value. Now with limited free time, I appreciate games that respect my schedule.\n\nGames that nailed the length:\n- Portal 2 (~8 hours)\n- Hades (~20 hours for first clear)\n- Outer Wilds (~15 hours)\n- Celeste (~12 hours)\n\nGames I loved but never finished because they are too long:\n- The Witcher 3\n- Red Dead Redemption 2\n- Baldur's Gate 3\n\nAnyone else feel this way or am I just getting old?",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.gaming,
      authorId: USER_IDS.techguru,
      createdAt: ago(8, 3),
      updatedAt: ago(8, 3),
      upvotes: 623,
      downvotes: 289,
      flair: "Discussion",
      spoiler: false,
      nsfw: false,
      awards: [],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // === science (posts 18-20) ===
    {
      id: makePostId(18),
      type: "link",
      title:
        "JWST captures high-resolution image of Proxima Centauri b atmosphere - water vapor detected",
      body: "",
      url: "https://www.nasa.gov/jwst",
      imageUrl: "",
      subredditId: SUB_IDS.science,
      authorId: USER_IDS.techguru,
      createdAt: ago(1, 2),
      updatedAt: ago(1, 2),
      upvotes: 6789,
      downvotes: 45,
      flair: "Space",
      spoiler: false,
      nsfw: false,
      awards: [
        {
          type: "platinum",
          givenBy: USER_IDS.demouser,
          givenAt: ago(1, 1),
        },
        {
          type: "gold",
          givenBy: USER_IDS.naturelover,
          givenAt: ago(0, 23),
        },
      ],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(19),
      type: "text",
      title:
        "New CRISPR technique achieves 99.7% accuracy in correcting sickle cell mutations in human trials",
      body: "A team at MIT has published results from a Phase III clinical trial showing near-perfect correction rates for sickle cell disease using a refined CRISPR-Cas9 delivery mechanism.\n\nKey findings:\n- 99.7% of treated cells showed successful gene correction\n- No off-target mutations detected in whole-genome sequencing\n- All 48 patients achieved sustained fetal hemoglobin production\n- Treatment is a one-time infusion requiring no immunosuppression\n\nThis could be the first true cure for sickle cell disease, affecting millions worldwide.",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.science,
      authorId: USER_IDS.techguru,
      createdAt: ago(3, 6),
      updatedAt: ago(3, 6),
      upvotes: 4523,
      downvotes: 23,
      flair: "Medicine",
      spoiler: false,
      nsfw: false,
      awards: [
        { type: "gold", givenBy: USER_IDS.demouser, givenAt: ago(3, 4) },
        {
          type: "gold",
          givenBy: USER_IDS.naturelover,
          givenAt: ago(3, 3),
        },
      ],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makePostId(20),
      type: "text",
      title:
        "Researchers develop plastic-eating enzyme that breaks down PET bottles in 24 hours at room temperature",
      body: "A breakthrough from the University of Tokyo: an engineered enzyme variant of PETase that operates efficiently at ambient temperature (20-25C), breaking down PET plastic into its monomers within 24 hours.\n\nPrevious PETase variants required temperatures above 60C. This new variant uses directed evolution to achieve:\n- 5x faster degradation rate\n- Activity at room temperature\n- Tolerance to common contaminants found in recycled plastic\n\nThe team estimates industrial-scale deployment could be feasible within 3-5 years.",
      url: "",
      imageUrl: "",
      subredditId: SUB_IDS.science,
      authorId: USER_IDS.naturelover,
      createdAt: ago(6, 10),
      updatedAt: ago(6, 10),
      upvotes: 3876,
      downvotes: 56,
      flair: "Environment",
      spoiler: false,
      nsfw: false,
      awards: [{ type: "silver", givenBy: USER_IDS.techguru, givenAt: ago(6, 8) }],
      crosspostedFrom: "",
      reported: false,
      reportReasons: [],
      removed: false,
    },
  ];

  // --- Comments ---
  const comments: Comment[] = [
    // Comments on post 1 (Rust article) - 3 levels deep
    {
      id: makeCommentId(1),
      postId: makePostId(1),
      parentId: "",
      authorId: USER_IDS.demouser,
      body: "Great write-up! I have been hesitant to try Rust because of the learning curve. How long did it take before you felt productive?",
      createdAt: ago(2, 4),
      updatedAt: ago(2, 4),
      upvotes: 89,
      downvotes: 2,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(2),
      postId: makePostId(1),
      parentId: makeCommentId(1),
      authorId: USER_IDS.techguru,
      body: "Honestly, about 3-4 weeks of daily use. The first week is brutal - you will fight the borrow checker constantly. By week 3 you start *thinking* in ownership semantics. By week 4 you wonder how you ever lived without it.\n\nI recommend starting with the Rustlings exercises and then building something small but real (a CLI tool is perfect).",
      createdAt: ago(2, 3, 30),
      updatedAt: ago(2, 3, 30),
      upvotes: 134,
      downvotes: 1,
      awards: [{ type: "silver", givenBy: USER_IDS.naturelover, givenAt: ago(2, 3) }],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(3),
      postId: makePostId(1),
      parentId: makeCommentId(2),
      authorId: USER_IDS.naturelover,
      body: "I second the Rustlings recommendation. Also, `cargo watch -x check` is a game changer - it re-runs the compiler every time you save a file.",
      createdAt: ago(2, 2),
      updatedAt: ago(2, 2),
      upvotes: 56,
      downvotes: 0,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(4),
      postId: makePostId(1),
      parentId: "",
      authorId: USER_IDS.naturelover,
      body: "Counterpoint: Go is still better for teams. The simplicity means any developer can read any Go code, which is huge for large orgs. Rust is great but the skill ceiling creates knowledge silos.",
      createdAt: ago(2, 3),
      updatedAt: ago(2, 3),
      upvotes: 45,
      downvotes: 38,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // Comments on post 6 (skill in your 20s) - 2 levels deep
    {
      id: makeCommentId(5),
      postId: makePostId(6),
      parentId: "",
      authorId: USER_IDS.techguru,
      body: 'Learning to cook properly. Not just "I can make pasta" but actually understanding flavor profiles, knife skills, and meal prep. It saves money, impresses dates, and is genuinely therapeutic after a long day of staring at code.',
      createdAt: ago(1, 3),
      updatedAt: ago(1, 3),
      upvotes: 567,
      downvotes: 8,
      awards: [{ type: "gold", givenBy: USER_IDS.demouser, givenAt: ago(1, 2) }],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(6),
      postId: makePostId(6),
      parentId: makeCommentId(5),
      authorId: USER_IDS.naturelover,
      body: "This is the answer. I started cooking seriously at 24 and it completely changed my relationship with food. Also, inviting people over for a home-cooked meal is the ultimate social move.",
      createdAt: ago(1, 2, 30),
      updatedAt: ago(1, 2, 30),
      upvotes: 234,
      downvotes: 3,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(7),
      postId: makePostId(6),
      parentId: "",
      authorId: USER_IDS.naturelover,
      body: "Public speaking. I was terrified of it but joined Toastmasters at 26. Within a year I went from shaking hands during presentations to genuinely enjoying it. It is the single most transferable skill in any career.",
      createdAt: ago(1, 2),
      updatedAt: ago(1, 2),
      upvotes: 412,
      downvotes: 5,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // Comments on post 10 (sunset photo) - 2 levels
    {
      id: makeCommentId(8),
      postId: makePostId(10),
      parentId: "",
      authorId: USER_IDS.demouser,
      body: "This is stunning. What time of year was this? I have been wanting to do a Big Sur road trip.",
      createdAt: ago(1, 18),
      updatedAt: ago(1, 18),
      upvotes: 78,
      downvotes: 1,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(9),
      postId: makePostId(10),
      parentId: makeCommentId(8),
      authorId: USER_IDS.naturelover,
      body: "Late October! The light is incredible around sunset during fall. Pro tip: check the Bixby Bridge viewpoint about 30 minutes before sunset for the best colors.",
      createdAt: ago(1, 17),
      updatedAt: ago(1, 17),
      upvotes: 45,
      downvotes: 0,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(10),
      postId: makePostId(10),
      parentId: "",
      authorId: USER_IDS.techguru,
      body: "r/pics has really been delivering lately. This is wallpaper-worthy.",
      createdAt: ago(1, 16),
      updatedAt: ago(1, 16),
      upvotes: 123,
      downvotes: 2,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // Comments on post 14 (Elden Ring)
    {
      id: makeCommentId(11),
      postId: makePostId(14),
      parentId: "",
      authorId: USER_IDS.techguru,
      body: "147 attempts on Malenia at level 1? That is absolutely insane. I struggled with her at level 150. What weapon did you end up using?",
      createdAt: ago(2, 7),
      updatedAt: ago(2, 7),
      upvotes: 234,
      downvotes: 3,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(12),
      postId: makePostId(14),
      parentId: makeCommentId(11),
      authorId: USER_IDS.demouser,
      body: "Dual cold uchigatanas with seppuku. The bleed and frost buildup is essential because your raw damage is garbage at base level. Also heavy use of the Blasphemous Blade weapon art for the healing.",
      createdAt: ago(2, 6, 30),
      updatedAt: ago(2, 6, 30),
      upvotes: 189,
      downvotes: 2,
      awards: [{ type: "silver", givenBy: USER_IDS.techguru, givenAt: ago(2, 6) }],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(13),
      postId: makePostId(14),
      parentId: makeCommentId(12),
      authorId: USER_IDS.naturelover,
      body: "Wait, you can use Blasphemous Blade at base level? I thought it had faith requirements.",
      createdAt: ago(2, 5),
      updatedAt: ago(2, 5),
      upvotes: 34,
      downvotes: 0,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // Comments on post 18 (JWST)
    {
      id: makeCommentId(14),
      postId: makePostId(18),
      parentId: "",
      authorId: USER_IDS.naturelover,
      body: "Water vapor in the atmosphere of a planet only 4 light-years away. Let that sink in. When I was in school they were not even sure exoplanets existed, and now we are analyzing their atmospheres.",
      createdAt: ago(1, 1),
      updatedAt: ago(1, 1),
      upvotes: 876,
      downvotes: 5,
      awards: [{ type: "gold", givenBy: USER_IDS.techguru, givenAt: ago(1, 0, 30) }],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(15),
      postId: makePostId(18),
      parentId: makeCommentId(14),
      authorId: USER_IDS.techguru,
      body: "Important caveat: water vapor does not mean liquid water, and liquid water does not mean habitability. Proxima b is tidally locked and in the path of intense stellar flares. But still, this is a remarkable technical achievement for JWST.",
      createdAt: ago(1, 0, 45),
      updatedAt: ago(1, 0, 45),
      upvotes: 543,
      downvotes: 4,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(16),
      postId: makePostId(18),
      parentId: "",
      authorId: USER_IDS.demouser,
      body: "The JWST has already exceeded all expectations. Every few weeks there is a new groundbreaking discovery. Best money NASA has ever spent.",
      createdAt: ago(0, 23),
      updatedAt: ago(0, 23),
      upvotes: 321,
      downvotes: 8,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // Comments on post 19 (CRISPR)
    {
      id: makeCommentId(17),
      postId: makePostId(19),
      parentId: "",
      authorId: USER_IDS.demouser,
      body: "As someone with a family member who has sickle cell, this brings me to tears. The pain crises are devastating and current treatments are limited. A one-time cure would be life-changing for millions.",
      createdAt: ago(3, 5),
      updatedAt: ago(3, 5),
      upvotes: 678,
      downvotes: 2,
      awards: [
        {
          type: "gold",
          givenBy: USER_IDS.naturelover,
          givenAt: ago(3, 4, 30),
        },
      ],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(18),
      postId: makePostId(19),
      parentId: makeCommentId(17),
      authorId: USER_IDS.naturelover,
      body: "I really hope the treatment becomes accessible globally and not just in wealthy countries. Sickle cell disproportionately affects populations in Sub-Saharan Africa where healthcare access is already limited.",
      createdAt: ago(3, 4),
      updatedAt: ago(3, 4),
      upvotes: 345,
      downvotes: 1,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },

    // Comments on post 20 (plastic enzyme)
    {
      id: makeCommentId(19),
      postId: makePostId(20),
      parentId: "",
      authorId: USER_IDS.techguru,
      body: "Before anyone gets too excited: breaking down PET into monomers is great, but you still need to re-polymerize those monomers to make new plastic. The energy cost of that step matters a lot for whether this is truly more sustainable than mechanical recycling.",
      createdAt: ago(6, 9),
      updatedAt: ago(6, 9),
      upvotes: 234,
      downvotes: 12,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
    {
      id: makeCommentId(20),
      postId: makePostId(20),
      parentId: makeCommentId(19),
      authorId: USER_IDS.naturelover,
      body: "True, but the advantage over mechanical recycling is that enzymatic depolymerization produces virgin-quality monomers. Mechanically recycled PET degrades in quality with each cycle. This could enable truly circular plastic recycling.",
      createdAt: ago(6, 8),
      updatedAt: ago(6, 8),
      upvotes: 189,
      downvotes: 3,
      awards: [],
      reported: false,
      reportReasons: [],
      removed: false,
    },
  ];

  return {
    users,
    subreddits,
    posts,
    comments,
    messages: [],
    currentUserId: "",
    theme: "light",
  };
}
