import type { User, Post, Story } from "./types";

export const CURRENT_USER_ID = "u1";
export const FOLLOWING_IDS = ["u2", "u3", "u4", "u5", "u6", "u7", "u8", "u9"];

export const SEED_USERS: User[] = [
  {
    id: "u1",
    username: "alex",
    name: "Alex Rivera",
    avatarUrl: "https://i.pravatar.cc/150?img=1",
    bio: "📸 Photography | ✈️ Travel | 🌿 Nature",
    followers: 1243,
    following: 891,
    postsCount: 47,
    hasStory: false,
    storyViewed: false,
  },
  {
    id: "u2",
    username: "emma_creates",
    name: "Emma Chen",
    avatarUrl: "https://i.pravatar.cc/150?img=2",
    bio: "🎨 Artist & illustrator | Making things beautiful ✨",
    followers: 28400,
    following: 312,
    postsCount: 234,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u3",
    username: "mike_travels",
    name: "Mike Torres",
    avatarUrl: "https://i.pravatar.cc/150?img=3",
    bio: "🌍 Exploring one city at a time | 47 countries",
    followers: 52100,
    following: 891,
    postsCount: 891,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u4",
    username: "sarah.bakes",
    name: "Sarah Kim",
    avatarUrl: "https://i.pravatar.cc/150?img=4",
    bio: "🍰 Pastry chef | 🎂 Custom cakes | Recipes ⬇️",
    followers: 15600,
    following: 203,
    postsCount: 412,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u5",
    username: "noah_lifts",
    name: "Noah Johnson",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    bio: "💪 Fitness | 🥗 Nutrition | Certified PT",
    followers: 8900,
    following: 445,
    postsCount: 178,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u6",
    username: "lily.designs",
    name: "Lily Park",
    avatarUrl: "https://i.pravatar.cc/150?img=6",
    bio: "🖌️ UX Designer | Minimalist | Coffee ☕",
    followers: 34200,
    following: 178,
    postsCount: 567,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u7",
    username: "carlos_foto",
    name: "Carlos Mendez",
    avatarUrl: "https://i.pravatar.cc/150?img=7",
    bio: "📷 Street photographer | 🌆 Urban | Based in NYC",
    followers: 67800,
    following: 321,
    postsCount: 1023,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u8",
    username: "zoe_wellness",
    name: "Zoe Williams",
    avatarUrl: "https://i.pravatar.cc/150?img=8",
    bio: "🧘 Yoga instructor | 🌿 Plant-based | Mindfulness",
    followers: 22300,
    following: 567,
    postsCount: 345,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u9",
    username: "jake_codes",
    name: "Jake Brown",
    avatarUrl: "https://i.pravatar.cc/150?img=9",
    bio: "👨‍💻 Full-stack dev | Open source | Building things 🚀",
    followers: 4500,
    following: 234,
    postsCount: 89,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u10",
    username: "diana_fashion",
    name: "Diana Lopez",
    avatarUrl: "https://i.pravatar.cc/150?img=10",
    bio: "👗 Fashion | OOTD | Collabs DM ✉️",
    followers: 143000,
    following: 892,
    postsCount: 2341,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u11",
    username: "ryan_outdoors",
    name: "Ryan Mitchell",
    avatarUrl: "https://i.pravatar.cc/150?img=11",
    bio: "🏔️ Hiker | Camper | 🌲 Pacific Northwest",
    followers: 31200,
    following: 445,
    postsCount: 678,
    hasStory: true,
    storyViewed: false,
  },
  {
    id: "u12",
    username: "sofia.eats",
    name: "Sofia Patel",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    bio: "🍜 Foodie | 📍 NYC | Restaurant reviews",
    followers: 89400,
    following: 1023,
    postsCount: 1456,
    hasStory: false,
    storyViewed: false,
  },
  {
    id: "u13",
    username: "max_music",
    name: "Max Schmidt",
    avatarUrl: "https://i.pravatar.cc/150?img=13",
    bio: "🎵 Producer | 🎹 Multi-instrumentalist | Tours soon",
    followers: 56700,
    following: 678,
    postsCount: 234,
    hasStory: false,
    storyViewed: false,
  },
  {
    id: "u14",
    username: "nina_art",
    name: "Nina Okafor",
    avatarUrl: "https://i.pravatar.cc/150?img=14",
    bio: "🎭 Fine artist | Commissions open | Exhibitions 🖼️",
    followers: 28900,
    following: 345,
    postsCount: 567,
    hasStory: false,
    storyViewed: false,
  },
  {
    id: "u15",
    username: "tom.architecture",
    name: "Tom Anderson",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    bio: "🏛️ Architect | Urban design | 📐 Sketches",
    followers: 41200,
    following: 234,
    postsCount: 789,
    hasStory: false,
    storyViewed: false,
  },
];

export const SEED_POSTS: Post[] = [
  {
    id: "p1",
    userId: "u2",
    imageUrl: "https://picsum.photos/seed/emma1/640/640",
    caption:
      "Working on a new series of watercolor illustrations 🎨 Each piece takes about 3 days. Worth every second. #watercolor #illustration #art #artistsoninstagram",
    likes: 3241,
    liked: false,
    saved: false,
    location: "Brooklyn, NY",
    timestamp: "2 hours ago",
    comments: [
      { id: "c1", userId: "u4", text: "This is absolutely stunning! 😍", timestamp: "1 hour ago" },
      { id: "c2", userId: "u6", text: "The colors are incredible 🌈", timestamp: "45 min ago" },
    ],
  },
  {
    id: "p2",
    userId: "u2",
    imageUrl: "https://picsum.photos/seed/emma2/640/640",
    caption: "Studio vibes on a Sunday afternoon ✨ #artstudio #creative #process",
    likes: 1823,
    liked: false,
    saved: false,
    timestamp: "1 day ago",
    comments: [
      { id: "c3", userId: "u3", text: "Love your workspace 🙌", timestamp: "20 hours ago" },
    ],
  },
  {
    id: "p3",
    userId: "u3",
    imageUrl: "https://picsum.photos/seed/mike1/640/640",
    caption:
      "Santorini at golden hour never gets old 🌅 The light here is unlike anything I've seen. #santorini #greece #travel #goldenhour",
    likes: 8934,
    liked: false,
    saved: false,
    location: "Santorini, Greece",
    timestamp: "3 hours ago",
    comments: [
      { id: "c4", userId: "u7", text: "That light is 🔥", timestamp: "2 hours ago" },
      { id: "c5", userId: "u1", text: "Adding this to my bucket list!", timestamp: "1 hour ago" },
    ],
  },
  {
    id: "p4",
    userId: "u3",
    imageUrl: "https://picsum.photos/seed/mike2/640/640",
    caption: "Lost in the medina 🕌 Morocco is endlessly fascinating. #morocco #marrakech #travel",
    likes: 5621,
    liked: false,
    saved: false,
    location: "Marrakech, Morocco",
    timestamp: "2 days ago",
    comments: [{ id: "c6", userId: "u8", text: "The colors!! 😍", timestamp: "2 days ago" }],
  },
  {
    id: "p5",
    userId: "u4",
    imageUrl: "https://picsum.photos/seed/sarah1/640/640",
    caption:
      "Six-layer lemon lavender cake for today's wedding 💛 I'll never get tired of that first slice reveal! #weddingcake #pastry",
    likes: 4512,
    liked: false,
    saved: false,
    location: "Seattle, WA",
    timestamp: "5 hours ago",
    comments: [
      { id: "c7", userId: "u2", text: "This is a work of art 🎂", timestamp: "4 hours ago" },
    ],
  },
  {
    id: "p6",
    userId: "u4",
    imageUrl: "https://picsum.photos/seed/sarah2/640/640",
    caption:
      "Croissant Sunday 🥐 Laminated dough is a labor of love but so worth it. #croissant #baking #frenchpastry",
    likes: 2341,
    liked: false,
    saved: false,
    timestamp: "4 days ago",
    comments: [],
  },
  {
    id: "p7",
    userId: "u5",
    imageUrl: "https://picsum.photos/seed/noah1/640/640",
    caption:
      "Morning session done ✅ 5am wake up never felt so good. Consistency is everything. #fitness #gym #morningworkout",
    likes: 1892,
    liked: false,
    saved: false,
    location: "Chicago, IL",
    timestamp: "6 hours ago",
    comments: [
      { id: "c8", userId: "u3", text: "You inspire me every day man 💪", timestamp: "5 hours ago" },
    ],
  },
  {
    id: "p8",
    userId: "u5",
    imageUrl: "https://picsum.photos/seed/noah2/640/640",
    caption:
      "Post-workout meal prep for the week 🥗 Protein, veggies, complex carbs. Simple and effective. #mealprep #nutrition",
    likes: 934,
    liked: false,
    saved: false,
    timestamp: "3 days ago",
    comments: [],
  },
  {
    id: "p9",
    userId: "u6",
    imageUrl: "https://picsum.photos/seed/lily1/640/640",
    caption:
      "New brand identity system shipped today 🎉 White space is not wasted space. #uxdesign #branding #minimalism",
    likes: 6723,
    liked: false,
    saved: true,
    location: "San Francisco, CA",
    timestamp: "7 hours ago",
    comments: [
      {
        id: "c9",
        userId: "u2",
        text: "The attention to detail is unreal 👏",
        timestamp: "6 hours ago",
      },
      { id: "c10", userId: "u7", text: "This is gorgeous", timestamp: "5 hours ago" },
    ],
  },
  {
    id: "p10",
    userId: "u6",
    imageUrl: "https://picsum.photos/seed/lily2/640/640",
    caption: "Redesigning the way we think about typography 🔤 #typographydesign #graphicdesign",
    likes: 4231,
    liked: false,
    saved: false,
    timestamp: "5 days ago",
    comments: [],
  },
  {
    id: "p11",
    userId: "u7",
    imageUrl: "https://picsum.photos/seed/carlos1/640/640",
    caption:
      "Rain-soaked streets of Midtown at 3am 🌧️ The city never really sleeps. #streetphotography #nyc #nightphotography",
    likes: 12431,
    liked: false,
    saved: false,
    location: "New York, NY",
    timestamp: "1 hour ago",
    comments: [
      {
        id: "c11",
        userId: "u3",
        text: "The mood in this photo is everything 😮",
        timestamp: "45 min ago",
      },
      { id: "c12", userId: "u6", text: "Incredible shot Carlos 🙏", timestamp: "30 min ago" },
    ],
  },
  {
    id: "p12",
    userId: "u7",
    imageUrl: "https://picsum.photos/seed/carlos2/640/640",
    caption:
      "Subway portraits series — #18. Everyone has a story. #subwayphotography #portraitphotography #nyc",
    likes: 9812,
    liked: false,
    saved: false,
    timestamp: "2 days ago",
    comments: [
      {
        id: "c13",
        userId: "u1",
        text: "This series is my favorite thing on Instagram",
        timestamp: "2 days ago",
      },
    ],
  },
  {
    id: "p13",
    userId: "u8",
    imageUrl: "https://picsum.photos/seed/zoe1/640/640",
    caption:
      "Sunrise flow on the beach 🌅🧘 Starting the week with intention and gratitude. #yoga #wellness #beachyoga",
    likes: 3241,
    liked: false,
    saved: false,
    location: "Malibu, CA",
    timestamp: "4 hours ago",
    comments: [
      { id: "c14", userId: "u4", text: "This looks so peaceful 🙏", timestamp: "3 hours ago" },
    ],
  },
  {
    id: "p14",
    userId: "u8",
    imageUrl: "https://picsum.photos/seed/zoe2/640/640",
    caption:
      "Plant-based bowl goals 🌿 Quinoa, roasted veggies, tahini drizzle. Link in bio for recipe! #plantbased #vegan",
    likes: 1823,
    liked: false,
    saved: false,
    timestamp: "3 days ago",
    comments: [],
  },
  {
    id: "p15",
    userId: "u9",
    imageUrl: "https://picsum.photos/seed/jake1/640/640",
    caption:
      "Finally shipped v2.0 after 6 months 🚀 Open source and free to use. Link in bio! #webdev #opensource #buildinpublic",
    likes: 892,
    liked: false,
    saved: false,
    timestamp: "8 hours ago",
    comments: [{ id: "c15", userId: "u2", text: "Congrats!! 🎉🎉", timestamp: "7 hours ago" }],
  },
  {
    id: "p16",
    userId: "u9",
    imageUrl: "https://picsum.photos/seed/jake2/640/640",
    caption:
      "Late night coding session ☕ New side project coming soon. Stay tuned. #coding #developer #sideproject",
    likes: 567,
    liked: false,
    saved: false,
    timestamp: "1 week ago",
    comments: [],
  },
  {
    id: "p17",
    userId: "u10",
    imageUrl: "https://picsum.photos/seed/diana1/640/640",
    caption: "SS26 editorial ✨ Fashion is art you wear. #fashion #editorial #style #ootd",
    likes: 45231,
    liked: false,
    saved: false,
    location: "Milan, Italy",
    timestamp: "1 day ago",
    comments: [],
  },
  {
    id: "p18",
    userId: "u10",
    imageUrl: "https://picsum.photos/seed/diana2/640/800",
    caption: "The bag of the season 👜 #fashionblogger #accessories #luxury",
    likes: 38900,
    liked: false,
    saved: false,
    timestamp: "3 days ago",
    comments: [],
  },
  {
    id: "p19",
    userId: "u11",
    imageUrl: "https://picsum.photos/seed/ryan1/640/640",
    caption:
      "Mount Rainier summit at 14,411ft 🏔️ Four years of training for this moment. #hiking #summitday #outdoors",
    likes: 12341,
    liked: false,
    saved: false,
    location: "Mount Rainier, WA",
    timestamp: "2 days ago",
    comments: [],
  },
  {
    id: "p20",
    userId: "u11",
    imageUrl: "https://picsum.photos/seed/ryan2/640/800",
    caption:
      "Campfire stories 🔥 Nothing beats falling asleep under the stars. #camping #nature #pnw",
    likes: 8923,
    liked: false,
    saved: false,
    timestamp: "5 days ago",
    comments: [],
  },
  {
    id: "p21",
    userId: "u12",
    imageUrl: "https://picsum.photos/seed/sofia1/640/640",
    caption:
      "Best ramen I've had all year 🍜 Little hole-in-the-wall in the East Village. #ramen #nycfood #foodie",
    likes: 23412,
    liked: false,
    saved: false,
    location: "East Village, NYC",
    timestamp: "6 hours ago",
    comments: [],
  },
  {
    id: "p22",
    userId: "u12",
    imageUrl: "https://picsum.photos/seed/sofia2/640/640",
    caption:
      "Omakase at Masa ✨ One of the most extraordinary dining experiences of my life. #omakase #sushi #nyc",
    likes: 31200,
    liked: false,
    saved: false,
    timestamp: "1 week ago",
    comments: [],
  },
  {
    id: "p23",
    userId: "u13",
    imageUrl: "https://picsum.photos/seed/max1/640/640",
    caption:
      "In the studio working on something special 🎵 Drop coming soon. #producer #music #studio",
    likes: 8934,
    liked: false,
    saved: false,
    location: "Los Angeles, CA",
    timestamp: "1 day ago",
    comments: [],
  },
  {
    id: "p24",
    userId: "u13",
    imageUrl: "https://picsum.photos/seed/max2/640/800",
    caption:
      "Setup upgraded 🎹 New sounds dropping this month. #homerecording #musicproduction #beats",
    likes: 6723,
    liked: false,
    saved: false,
    timestamp: "4 days ago",
    comments: [],
  },
  {
    id: "p25",
    userId: "u14",
    imageUrl: "https://picsum.photos/seed/nina1/640/640",
    caption:
      "Finished piece for the Lagos Art Week exhibition 🖼️ Oil on canvas, 120x160cm. DM for commissions. #finearts #oilpainting",
    likes: 15234,
    liked: false,
    saved: false,
    location: "Lagos, Nigeria",
    timestamp: "2 days ago",
    comments: [],
  },
  {
    id: "p26",
    userId: "u14",
    imageUrl: "https://picsum.photos/seed/nina2/640/800",
    caption:
      "Process shot — this one took 3 weeks but I love how the light came out 🌟 #wip #artstudio #paintingprocess",
    likes: 9812,
    liked: false,
    saved: false,
    timestamp: "1 week ago",
    comments: [],
  },
  {
    id: "p27",
    userId: "u15",
    imageUrl: "https://picsum.photos/seed/tom1/640/640",
    caption:
      "Herzog & de Meuron's Elbphilharmonie at dusk 🏛️ Architecture that makes you feel small in the best way. #architecture #hamburg",
    likes: 18923,
    liked: false,
    saved: false,
    location: "Hamburg, Germany",
    timestamp: "3 days ago",
    comments: [],
  },
  {
    id: "p28",
    userId: "u15",
    imageUrl: "https://picsum.photos/seed/tom2/640/800",
    caption:
      "Structural sketch series, no. 34 📐 Back to basics with pencil and paper. #architecturaldrawing #sketch",
    likes: 7234,
    liked: false,
    saved: false,
    timestamp: "6 days ago",
    comments: [],
  },
  {
    id: "p29",
    userId: "u1",
    imageUrl: "https://picsum.photos/seed/alex1/640/640",
    caption:
      "Golden hour at the park 🌅 Sometimes you just need to step outside. #photography #goldenhour #nature",
    likes: 234,
    liked: false,
    saved: false,
    location: "Central Park, NYC",
    timestamp: "1 week ago",
    comments: [],
  },
  {
    id: "p30",
    userId: "u1",
    imageUrl: "https://picsum.photos/seed/alex2/640/640",
    caption: "Film dump from last weekend 📷 #35mm #filmphoto #analog",
    likes: 189,
    liked: false,
    saved: false,
    timestamp: "2 weeks ago",
    comments: [],
  },
];

export const SEED_STORIES: Story[] = [
  {
    id: "s1",
    userId: "u2",
    imageUrl: "https://picsum.photos/seed/story-emma/640/1136",
    viewed: false,
    timestamp: "2 hours ago",
  },
  {
    id: "s2",
    userId: "u3",
    imageUrl: "https://picsum.photos/seed/story-mike/640/1136",
    viewed: false,
    timestamp: "3 hours ago",
  },
  {
    id: "s3",
    userId: "u4",
    imageUrl: "https://picsum.photos/seed/story-sarah/640/1136",
    viewed: false,
    timestamp: "1 hour ago",
  },
  {
    id: "s4",
    userId: "u5",
    imageUrl: "https://picsum.photos/seed/story-noah/640/1136",
    viewed: false,
    timestamp: "5 hours ago",
  },
  {
    id: "s5",
    userId: "u6",
    imageUrl: "https://picsum.photos/seed/story-lily/640/1136",
    viewed: false,
    timestamp: "4 hours ago",
  },
  {
    id: "s6",
    userId: "u7",
    imageUrl: "https://picsum.photos/seed/story-carlos/640/1136",
    viewed: false,
    timestamp: "1 hour ago",
  },
  {
    id: "s7",
    userId: "u8",
    imageUrl: "https://picsum.photos/seed/story-zoe/640/1136",
    viewed: false,
    timestamp: "6 hours ago",
  },
  {
    id: "s8",
    userId: "u9",
    imageUrl: "https://picsum.photos/seed/story-jake/640/1136",
    viewed: false,
    timestamp: "2 hours ago",
  },
  {
    id: "s9",
    userId: "u10",
    imageUrl: "https://picsum.photos/seed/story-diana/640/1136",
    viewed: false,
    timestamp: "30 min ago",
  },
  {
    id: "s10",
    userId: "u11",
    imageUrl: "https://picsum.photos/seed/story-ryan/640/1136",
    viewed: false,
    timestamp: "45 min ago",
  },
];
